language: haskell
matrix:
  include:
  - ghc: "7.2"
    install: cabal install --only-dependencies --enable-tests --dependency=doctest=doctest-0.13
    script: cabal configure --enable-tests --dependency=doctest=doctest-0.13 && cabal build && cabal test binary-tree-test
  - ghc: "7.4"
    script: cabal configure --enable-tests && cabal build && cabal test binary-tree-test
  - ghc: "7.6"
    script: cabal configure --enable-tests && cabal build && cabal test binary-tree-test
  - ghc: "7.8"
    script: cabal configure --enable-tests && cabal build && cabal test binary-tree-test
  - ghc: "7.10"
  - ghc: "8.0"
  - ghc: "8.2"
