name:                binary-tree
version:             0.1.0.0
github:              "oisdk/binary-tree"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/oisdk/binary-tree#readme>

dependencies:
- base >= 4.0 && < 5

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
    - -fwarn-redundant-constraints
    - -Wcompat

library:
  source-dirs: src
  dependencies:
  - deepseq
  when:
    - condition: impl(ghc)
      dependencies:
      - ghc-prim

tests:
  binary-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary-tree
    - QuickCheck >= 2.7.1
    - checkers
    - ChasingBottoms
    - HUnit
    - test-framework
    - test-framework-quickcheck2
  doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - binary-tree
    - doctest
    - QuickCheck >= 2.7.1

benchmarks:
  bench:
    main: bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - binary-tree
    - criterion
    - random
