name:                binary-tree
version:             0.1.0.0
github:              "oisdk/binary-tree"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/binary-tree#readme>

dependencies:
- base >= 4.0 && < 5

library:
  source-dirs: src
  when:
    - condition: impl(ghc)
      then:
        dependencies:
        - deepseq
        - ghc-prim
      else:
        dependencies:
        - deepseq
  ghc-options:
  - -Wall

tests:
  binary-tree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - binary-tree
    - QuickCheck >= 2.7.1
    - checkers
    - ChasingBottoms
    - HUnit
    - test-framework
    - test-framework-quickcheck2
  doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - binary-tree
    - doctest
    - QuickCheck >= 2.7.1
